languageCode = 'en-us'
title = 'sec-feed'
theme = "minimal"

[params]
    showBorder = true
    backgroundColor = "white"

[[menu.main]]
    url = "/cve/"
    name = "list"
    weight = 1

[[menu.main]]
    url = "/tags/"
    name = "tags"
    weight = 2